# Assignment-2 COMP90024

# Cluster and Cloud Computing - Team 4


couch_instances:
  - name: db-server-1
    volumes: ["vol11", "vol12"]
  - name: db-server-2
    volumes: ["vol21"]

volumes:
  - device: /dev/vdb
    mountpoint: /var/lib/docker

db_username: admin
db_password: admin

