# Assignment-2 COMP90024

# Cluster and Cloud Computing - Team 4

# Common vars

# Availability Zone

availability_zone: melbourne-qh2-uom

instance_image: 356ff1ed-5960-4ac2-96a1-0c0198e6a999
instance_key_name: cc_assign2

# Flavor
instance_flavor: uom.mse.2c9g
web_instance_flavor: uom.mse.1c4g

# Volume
volumes:
  - vol_name: vol11
    vol_size: 25
  - vol_name: vol12
    vol_size: 25
  - vol_name: vol21
    vol_size: 40
  - vol_name: vol31
    vol_size: 10

# Security group
security_groups:
  - name: ssh
    description: "Security group for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0

  - name: couchdb
    description: "CouchDB access" 
    protocol: tcp
    port_range_min: 5984
    port_range_max: 5984
    remote_ip_prefix: 0.0.0.0/0

  - name: http
    description: "Security group for HTTP access"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0

  - name: intra_cluster_comm1
    description: "Communication access 1" 
    protocol: tcp
    port_range_min: 9100
    port_range_max: 9200
    remote_ip_prefix: 0.0.0.0/0

  - name: intra_cluster_comm2
    description: "Communication access 2"
    protocol: tcp
    port_range_min: 4369
    port_range_max: 4369
    remote_ip_prefix: 0.0.0.0/0              

# Instance
instances:
  - name: db-server-1
    volumes: ['vol11', 'vol12']
  - name: db-server-2
    volumes: ['vol21']

web_instance: 
  - name: web-app
    volumes: ['vol31']



