version: '3'

services:

  app:
    container_name: webapp
    restart: always
    build: .
    networks:
      - webappnet
    ports:
      - "5000:5000"

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    networks:
      - webappnet
    ports:
      - "80:8080"

networks:
  webappnet:
