# -*- coding: utf-8 -*-
"""web_app.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mn_qLGYpTplw9cZJRWcfbcENiARKYtGD
"""

import tweepy
from tweepy import OAuthHandler
import os
import re
import time
from dbconnector import Couch



# ip address for the master node from ip.txt file
ip_file=open("ip.txt", "r")
couchdb_master_ip=ip_file.readline().rstrip()
ip_file.close()


# couchdb connection class instance created
couch=Couch('http://'+couchdb_master_ip+':5984/',['tweet'])

# Getting various tweetapi from database
api=couch.getdata('tweet_api')

#authentication for twitter
api_key = api['Api_Key']
api_secret = api['Api_Secret_Key']
access_token = api['Access_Token']
access_token_secret = api['Access_Secret_Token']

authorizer = OAuthHandler(api_key, api_secret)
authorizer.set_access_token(access_token, access_token_secret)
api = tweepy.API(authorizer, timeout=15, wait_on_rate_limit=True)



# Getting tweets 
while True:
    
    
    # code fetching from db
    loc=couch.getdata('subregion')
    place=loc['code']
    


    #tweets collection
    tweets_collector = []
  
    try:
        
        
        for tweet in tweepy.Cursor(api.search_tweets, q="place:%s" % place, lang='en', result_type='recent', tweet_mode='extended').items(1000):
            tweets_collector.append({"tweet_id":str(tweet.id), "text":str(tweet.full_text),"city":str(tweet.place.name)})
       
        counter = 0
        # Pushing tweets to db
        for i in tweets_collector:
            couch.pushdata(i,'tweet')
            if(counter %100 == 0):
              print(i)
            counter += 1  

            
    except:
        pass

    # Reset the flag in region database
    couch.resetflag('code',place,'subregion')
    del(tweets_collector)
    #print("--- %s seconds ---" % (time.time() - start_time))
    time.sleep(40)
