
# Install pip
- name: Install pip
  become: yes
  apt:
    name: ['python3-pip']
    state: latest
  when: ansible_distribution == "Ubuntu"

# Update pip
- name: Update pip
  pip:
    name: ['pip']
    state: latest

# pip install && pip install openstacksdk

- name: Install openstacksdk
  pip:
     name: ["openstacksdk==0.52"]
     state: latest

